<div>
	<ul class="mainnav">
	<li class="heading">Welcome to MAASL</li>
	<li><a href="index.shtml">MAASL Home Page</a></li>
	<li><a href="about.shtml">About Us</a></li>
	<li><a href="board.shtml">Board of Directors</a></li>
	<li><a href="shop.shtml">Buy MAASL Gear</a></li>
	<li><a href="fields.shtml">Fields</a></li>
	<li><a href="faq.shtml">Frequently Asked Questions</a></li>
	<li><a href="schedule.shtml">Game Schedule</a></li>
	<li><a href="links.shtml">Links &amp; Upcoming Events</a></li>
	<li><a href="register.shtml">Register for MAASL</a></li>
	<li><a href="rosters.shtml">Team Rosters</a></li>
	</ul>
</div>
